name: Run bash script

on:
  repository_dispatch:
    types: [bash]

jobs:
  bash:
    runs-on: ubuntu-latest
    permissions:
      contents: read # todo
    steps:
      - name: Execute
        id: bash
        run: bash ./resources/bash/script.sh