name: Hello World

on:
  repository_dispatch:
    types: [hello]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read # todo
    steps:
      - name: Hello World
        id: hello
        run: echo "hello world"